trigger:
  paths:
    include:
      - todos-api/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'todos-api'
  acrLoginServer: 'mytodosacr.azurecr.io'
  dockerRegistryServiceConnection: 'acr-connection' # Docker Registry SC name
  azureWebAppName: 'TODOs-API'                 # Azure Web App name
  azureSubscription: 'PipelineConnection'        # ARM SC name
  JWT_SECRET: PRFT 
  REDIS_HOST: redisTODO.redis.cache.windows.net 
  REDIS_PORT: 6380 
  REDIS_CHANNEL: log_channel

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Image
    jobs:
      - job: Docker
        steps:
          - task: Docker@2
            displayName: Build and push image to ACR
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: $(imageName)
              command: buildAndPush
              Dockerfile: todos-api/Dockerfile
              buildContext: todos-api
              tags: |
                $(Build.BuildId)
              envVars: |
                JWT_SECRET=$(JWT_SECRET)
                AUTH_API_PORT=$(AUTH_API_PORT)
                USERS_API_ADDRESS=$(USERS_API_ADDRESS)

  - stage: Deploy
    displayName: Deploy to Azure Web App
    dependsOn: BuildAndPush
    jobs:
      - job: DeployWebApp
        steps:
          - task: AzureWebAppContainer@1
            displayName: Deploy image to Azure Web App
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(azureWebAppName)
              containers: |
                $(acrLoginServer)/$(imageName):$(Build.BuildId)
