trigger:
  paths:
    include:
      - users-api/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'users-api'
  acrLoginServer: 'mytodosacr.azurecr.io'
  dockerRegistryServiceConnection: 'acr-connection' # Docker Registry SC name
  azureWebAppName: 'USERS-API'                 # Azure Web App name
  azureSubscription: 'PipelineConnection'        # ARM SC name

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Image
    jobs:
      - job: Docker
        steps:
          - task: Docker@2
            displayName: Build and push image to ACR
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: $(imageName)
              command: buildAndPush
              Dockerfile: users-api/Dockerfile
              buildContext: users-api
              tags: |
                $(Build.BuildId)

  - stage: Deploy
    displayName: Deploy to Azure Web App
    dependsOn: BuildAndPush
    jobs:
      - job: DeployWebApp
        steps:
          - task: AzureWebAppContainer@1
            displayName: Deploy image to Azure Web App
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(azureWebAppName)
              containers: |
                $(acrLoginServer)/$(imageName):$(Build.BuildId)
